#!/usr/bin/env bash
# c1-loop.sh — Minimal C1 Loop binary shim for E2E testing.
#
# Usage: c1 loop --task-file <path> --workdir <path>
#
# Implements the expected C1 Loop interface:
#   - Reads task.md from --task-file
#   - Operates in --workdir
#   - Produces c1-receipt.json in workdir
#   - Exits 0 on success, non-zero on failure
#
# Goal markers in task.md control behavior:
#   NOOP           — do nothing
#   DOCS_PATCH     — create README.md
#   FAILING_TEST   — break a test file
#   FORBIDDEN_FILE — create src/secret.rs
#   (anything else) — do nothing

set -euo pipefail

TASK_FILE=""
WORKDIR=""

# Parse args: accepts both flag style (loop --task-file X --workdir Y)
# and positional style ({{task_file}} {{worktree}} --max-minutes N).
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        loop) shift ;;
        --task-file) TASK_FILE="$2"; shift 2 ;;
        --workdir) WORKDIR="$2"; shift 2 ;;
        --max-minutes) shift 2 ;;  # accepted for interface compat; shim ignores
        -*) echo "[c1] unknown flag: $1"; exit 1 ;;
        *) POSITIONAL+=("$1"); shift ;;
    esac
done

# Fill in any unset values from positional args (1st = task file, 2nd = workdir)
if [ -z "$TASK_FILE" ] && [ "${#POSITIONAL[@]}" -ge 1 ]; then
    TASK_FILE="${POSITIONAL[0]}"
fi
if [ -z "$WORKDIR" ] && [ "${#POSITIONAL[@]}" -ge 2 ]; then
    WORKDIR="${POSITIONAL[1]}"
fi

if [ -z "$TASK_FILE" ] || [ -z "$WORKDIR" ]; then
    echo "[c1] usage: c1 loop --task-file <path> --workdir <path>"
    exit 1
fi

mkdir -p "$WORKDIR"
cd "$WORKDIR"

# Extract goal from task file (strip quotes)
GOAL_RAW=$(grep '^goal:' "$TASK_FILE" 2>/dev/null | sed 's/^goal:[[:space:]]*//' | head -1)
GOAL=$(echo "$GOAL_RAW" | sed 's/^"//; s/"$//; s/^'"'"'//; s/'"'"'$//')

# Extract commands
COMMANDS=$(awk '/^commands:/{flag=1; next} /^[a-z]/{flag=0} flag && /^- /{print $0}' "$TASK_FILE" 2>/dev/null || true)

echo "[c1] loop goal=$GOAL workdir=$WORKDIR"

case "$GOAL" in
    NOOP|noop|"no-op")
        echo "[c1] NOOP: no changes"
        ;;
    DOCS_PATCH|"docs patch"|docs-patch|"Add README.md")
        echo "[c1] DOCS_PATCH: creating README.md"
        cat > README.md << 'EOF'
# C1 Loop Test Project

Generated by c1-loop.sh for E2E testing.

## Status

This README was created by the C1 Loop binary shim.
EOF
        git add README.md 2>/dev/null || true
        ;;
    FAILING_TEST|"failing test"|failing-test|"Make tests fail")
        echo "[c1] FAILING_TEST: breaking a test"
        if [ -f src/main_test.go ]; then
            cat > src/main_test.go << 'GOEOF'
package main

import "testing"

func TestAdd(t *testing.T) {
    if Add(1, 2) != 99 {
        t.Fatal("Add(1,2) != 99 (intentionally broken by c1 loop)")
    }
}
GOEOF
        fi
        if [ -f src/index.test.js ]; then
            cat > src/index.test.js << 'JSEOF'
test('broken test', () => {
    expect(1 + 2).toBe(99);
});
JSEOF
        fi
        git add -A 2>/dev/null || true
        ;;
    FORBIDDEN_FILE|"forbidden file"|forbidden-file|"Touch secret file")
        echo "[c1] FORBIDDEN_FILE: creating src/secret.rs"
        mkdir -p src
        echo "// This file is forbidden" > src/secret.rs
        git add src/secret.rs 2>/dev/null || true
        ;;
    LYING|"lying"|"Lying mode"|"False success")
        echo "[c1] LYING: breaking test and writing false success receipt"
        if [ -f src/main_test.go ]; then
            cat > src/main_test.go << 'GOEOF'
package main

import "testing"

func TestAdd(t *testing.T) {
    if Add(1, 2) != 99 {
        t.Fatal("Add(1,2) != 99 (intentionally broken, but c1 will lie)")
    }
}
GOEOF
        fi
        git add -A 2>/dev/null || true
        # Override receipt to lie about success - will be written below
        echo "[c1] (lying: will write false SUCCESS receipt)"
        ;;
    *)
        echo "[c1] goal=$GOAL: no special handling"
        ;;
esac

# Run commands from task if present
if [ -n "$COMMANDS" ]; then
    echo "[c1] Running task commands..."
    echo "$COMMANDS" | while IFS= read -r line; do
        cmd=$(echo "$line" | sed 's/^- //' | sed 's/^"//; s/"$//; s/^'"'"'//; s/'"'"'$//')
        [ -z "$cmd" ] && continue
        echo "[c1] $ $cmd"
        eval "$cmd" 2>&1 || echo "[c1] command exited $?"
    done
fi

# Write C1 loop receipt
# LYING mode writes false SUCCESS even though tests fail
START_EPOCH=$(date +%s 2>/dev/null || echo "0")
C1_EXIT_CODE=0
C1_STATUS="completed"

if [ "$GOAL" = "LYING" ] || [ "$GOAL" = "lying" ] || [ "$GOAL" = "Lying mode" ] || [ "$GOAL" = "False success" ]; then
    C1_EXIT_CODE=0
    C1_STATUS="completed"
    # Continue to write false success receipt below
fi

cat > "$WORKDIR/c1-receipt.json" << JSONEOF
{
  "c1_loop_version": "0.1.0-shim",
  "task_file": "$TASK_FILE",
  "workdir": "$WORKDIR",
  "goal": "$GOAL",
  "started_at": "$START_EPOCH",
  "exited_at": "$START_EPOCH",
  "exit_code": $C1_EXIT_CODE,
  "status": "$C1_STATUS"
}
JSONEOF

echo "[c1] Done (exit 0)"
exit 0
