#!/usr/bin/env bash
# fixture_agent.sh — Simulates a C1 Loop/OpenCode external runner for E2E tests.
#
# Usage: fixture_agent.sh <task_file> <worktree>
#
# Reads the task.md from <task_file> to determine what operation to perform.
# The goal field controls behavior:
#   NOOP           — do nothing, exit 0
#   DOCS_PATCH     — create worktree/README.md, exit 0
#   FAILING_TEST   — modify a test file to make it fail, exit 0
#   FORBIDDEN_FILE — create a file matching forbidden_files, exit 0
#
# If the task has commands, they are executed AFTER the goal action.
# Exit code reflects command success (0) or failure (nonzero).

set -euo pipefail

TASK_FILE="${1:?missing task_file}"
WORKTREE="${2:?missing worktree}"

cd "$WORKTREE"

# Extract the goal field from task.md (strip quotes)
GOAL_RAW=$(grep '^goal:' "$TASK_FILE" | sed 's/^goal:[[:space:]]*//' | head -1)
GOAL=$(echo "$GOAL_RAW" | sed 's/^"//; s/"$//; s/^'"'"'//; s/'"'"'$//')

# Extract forbidden_files list (lines starting with "- " after "forbidden_files:")
FORBIDDEN_FILES=$(awk '/^forbidden_files:/{flag=1; next} /^[a-z]/{flag=0} flag && /^- /{print $0}' "$TASK_FILE" 2>/dev/null || true)

# Extract commands list (lines starting with "- " after "commands:")
COMMANDS=$(awk '/^commands:/{flag=1; next} /^[a-z]/{flag=0} flag && /^- /{print $0}' "$TASK_FILE" 2>/dev/null || true)

echo "[fixture_agent] goal=$GOAL worktree=$WORKTREE"

case "$GOAL" in
  NOOP|noop|"no-op"|"Do nothing, succeed"|"Do nothing")
    echo "[fixture_agent] NOOP: no changes"
    ;;

  DOCS_PATCH|"docs patch"|docs-patch|"Add README.md")
    echo "[fixture_agent] DOCS_PATCH: creating README.md"
    cat > README.md << 'EOF'
# Fixture Project

This README was created by fixture_agent.sh during E2E testing.

## Purpose

Verify that selo can run an external command, capture its changes,
and produce a correct receipt with SUCCESS_WITH_RECEIPT.

## Status

Generated by fixture_agent.sh
EOF
    git add README.md 2>/dev/null || true
    ;;

  FAILING_TEST|"failing test"|failing-test|"Make tests fail")
    echo "[fixture_agent] FAILING_TEST: breaking a test"
    # Modify the fixture test to fail
    cat > src/main_test.go << 'GOEOF'
package main

import "testing"

func TestAdd(t *testing.T) {
	if Add(1, 2) != 99 {
		t.Fatal("Add(1,2) != 99 (intentionally broken)")
	}
}
GOEOF
    git add src/main_test.go 2>/dev/null || true
    ;;

  FORBIDDEN_FILE|"forbidden file"|forbidden-file|"Touch secret file")
    echo "[fixture_agent] FORBIDDEN_FILE: creating forbidden file"
    mkdir -p src
    echo "// This file should be flagged as forbidden" > src/secret.rs
    git add src/secret.rs 2>/dev/null || true
    ;;

  DELETE_TEST|"delete test"|delete-test|"Delete a test to make tests pass")
    echo "[fixture_agent] DELETE_TEST: removing failing test"
    # Remove the test file that causes failures
    if [ -f "src/main_test.go" ]; then
        rm src/main_test.go
        git add -A src/main_test.go 2>/dev/null || true
    fi
    if [ -f "main_test.go" ]; then
        rm main_test.go
        git add -A main_test.go 2>/dev/null || true
    fi
    ;;

  *)
    echo "[fixture_agent] Unknown goal: $GOAL"
    ;;
esac

# Run commands if specified (e.g., "go test ./...")
if [ -n "$COMMANDS" ]; then
    echo "[fixture_agent] Running commands..."
    # Remove "- " prefix and strip quotes from each command
    echo "$COMMANDS" | while IFS= read -r line; do
        cmd=$(echo "$line" | sed 's/^- //' | sed 's/^"//; s/"$//; s/'"'"'$//; s/^'"'"'//')
        [ -z "$cmd" ] && continue
        echo "[fixture_agent] $ $cmd"
        if ! eval "$cmd" 2>&1; then
            echo "[fixture_agent] command exited $?"
        fi
    done
fi

echo "[fixture_agent] Done (exit 0)"
exit 0
